---
- hosts: localhost
  connection: local
  vars:
    aws_region: us-east-1
    instance_id: i-0e09ecc2b1059fc95

  tasks:
  - name: Shutdown an instance with public IP address
    amazon.aws.ec2_instance:
      region: "{{ aws_region }}"
      instance_ids: "{{ instance_id }}"
      state: stopped
      wait: True
      vpc_subnet_id: subnet-01dc37a8491175268
      assign_public_ip: yes
    register: stop_result

  - name: Print stop result
    debug:
      var: stop_result
